// @generated by protoc-gen-es v2.8.0 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/common.proto (package budget.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file budget/v1/common.proto.
 */
export const file_budget_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChZidWRnZXQvdjEvY29tbW9uLnByb3RvEglidWRnZXQudjEiMwoFTW9uZXkSFQoNY3VycmVuY3lfY29kZRgBIAEoCRITCgttaW5vcl91bml0cxgCIAEoAyKRAQoGRnhJbmZvEhoKEmZyb21fY3VycmVuY3lfY29kZRgBIAEoCRIYChB0b19jdXJyZW5jeV9jb2RlGAIgASgJEhQKDHJhdGVfZGVjaW1hbBgDIAEoCRIpCgVhc19vZhgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEAoIcHJvdmlkZXIYBSABKAkiPAoLUGFnZVJlcXVlc3QSDAoEcGFnZRgBIAEoBRIRCglwYWdlX3NpemUYAiABKAUSDAoEc29ydBgDIAEoCSJZCgxQYWdlUmVzcG9uc2USDAoEcGFnZRgBIAEoBRIRCglwYWdlX3NpemUYAiABKAUSEwoLdG90YWxfaXRlbXMYAyABKAMSEwoLdG90YWxfcGFnZXMYBCABKAUiXQoJRGF0ZVJhbmdlEigKBGZyb20YASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEiYKAnRvGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCpuCg9UcmFuc2FjdGlvblR5cGUSIAocVFJBTlNBQ1RJT05fVFlQRV9VTlNQRUNJRklFRBAAEhsKF1RSQU5TQUNUSU9OX1RZUEVfSU5DT01FEAESHAoYVFJBTlNBQ1RJT05fVFlQRV9FWFBFTlNFEAIqYgoMQ2F0ZWdvcnlLaW5kEh0KGUNBVEVHT1JZX0tJTkRfVU5TUEVDSUZJRUQQABIYChRDQVRFR09SWV9LSU5EX0lOQ09NRRABEhkKFUNBVEVHT1JZX0tJTkRfRVhQRU5TRRACQjhaNmdpdGh1Yi5jb20vcG9zaXRyb240OC9idWRnZXQvZ2VuL2dvL2J1ZGdldC92MTtidWRnZXR2MWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Generic money representation using minor currency units (e.g., cents)
 *
 * @generated from message budget.v1.Money
 */
export type Money = Message<"budget.v1.Money"> & {
  /**
   * ISO 4217, e.g. "USD", "EUR", "RUB"
   *
   * @generated from field: string currency_code = 1;
   */
  currencyCode: string;

  /**
   * integer number of minor units (cents/kopecks)
   *
   * @generated from field: int64 minor_units = 2;
   */
  minorUnits: bigint;
};

/**
 * Describes the message budget.v1.Money.
 * Use `create(MoneySchema)` to create a new message.
 */
export const MoneySchema: GenMessage<Money> = /*@__PURE__*/
  messageDesc(file_budget_v1_common, 0);

/**
 * Foreign exchange info applied to a conversion at a specific date
 * Semantics: to_amount = from_amount * rate_decimal
 *
 * @generated from message budget.v1.FxInfo
 */
export type FxInfo = Message<"budget.v1.FxInfo"> & {
  /**
   * original currency
   *
   * @generated from field: string from_currency_code = 1;
   */
  fromCurrencyCode: string;

  /**
   * target/base currency
   *
   * @generated from field: string to_currency_code = 2;
   */
  toCurrencyCode: string;

  /**
   * decimal string, e.g. "92.3456"
   *
   * @generated from field: string rate_decimal = 3;
   */
  rateDecimal: string;

  /**
   * date/time the rate was taken for
   *
   * @generated from field: google.protobuf.Timestamp as_of = 4;
   */
  asOf?: Timestamp;

  /**
   * e.g. "ecb", "cbr", "manual"
   *
   * @generated from field: string provider = 5;
   */
  provider: string;
};

/**
 * Describes the message budget.v1.FxInfo.
 * Use `create(FxInfoSchema)` to create a new message.
 */
export const FxInfoSchema: GenMessage<FxInfo> = /*@__PURE__*/
  messageDesc(file_budget_v1_common, 1);

/**
 * @generated from message budget.v1.PageRequest
 */
export type PageRequest = Message<"budget.v1.PageRequest"> & {
  /**
   * 1-based
   *
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * max enforced server-side
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * e.g. "occurred_at desc"
   *
   * @generated from field: string sort = 3;
   */
  sort: string;
};

/**
 * Describes the message budget.v1.PageRequest.
 * Use `create(PageRequestSchema)` to create a new message.
 */
export const PageRequestSchema: GenMessage<PageRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_common, 2);

/**
 * @generated from message budget.v1.PageResponse
 */
export type PageResponse = Message<"budget.v1.PageResponse"> & {
  /**
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * @generated from field: int64 total_items = 3;
   */
  totalItems: bigint;

  /**
   * @generated from field: int32 total_pages = 4;
   */
  totalPages: number;
};

/**
 * Describes the message budget.v1.PageResponse.
 * Use `create(PageResponseSchema)` to create a new message.
 */
export const PageResponseSchema: GenMessage<PageResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_common, 3);

/**
 * @generated from message budget.v1.DateRange
 */
export type DateRange = Message<"budget.v1.DateRange"> & {
  /**
   * @generated from field: google.protobuf.Timestamp from = 1;
   */
  from?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp to = 2;
   */
  to?: Timestamp;
};

/**
 * Describes the message budget.v1.DateRange.
 * Use `create(DateRangeSchema)` to create a new message.
 */
export const DateRangeSchema: GenMessage<DateRange> = /*@__PURE__*/
  messageDesc(file_budget_v1_common, 4);

/**
 * @generated from enum budget.v1.TransactionType
 */
export enum TransactionType {
  /**
   * @generated from enum value: TRANSACTION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TRANSACTION_TYPE_INCOME = 1;
   */
  INCOME = 1,

  /**
   * @generated from enum value: TRANSACTION_TYPE_EXPENSE = 2;
   */
  EXPENSE = 2,
}

/**
 * Describes the enum budget.v1.TransactionType.
 */
export const TransactionTypeSchema: GenEnum<TransactionType> = /*@__PURE__*/
  enumDesc(file_budget_v1_common, 0);

/**
 * @generated from enum budget.v1.CategoryKind
 */
export enum CategoryKind {
  /**
   * @generated from enum value: CATEGORY_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CATEGORY_KIND_INCOME = 1;
   */
  INCOME = 1,

  /**
   * @generated from enum value: CATEGORY_KIND_EXPENSE = 2;
   */
  EXPENSE = 2,
}

/**
 * Describes the enum budget.v1.CategoryKind.
 */
export const CategoryKindSchema: GenEnum<CategoryKind> = /*@__PURE__*/
  enumDesc(file_budget_v1_common, 1);

