// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/currency_exchange.proto (package budget.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Money, PageRequest, PageResponse } from "./common_pb";
import { file_budget_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file budget/v1/currency_exchange.proto.
 */
export const file_budget_v1_currency_exchange: GenFile = /*@__PURE__*/
  fileDesc("CiFidWRnZXQvdjEvY3VycmVuY3lfZXhjaGFuZ2UucHJvdG8SCWJ1ZGdldC52MSKTAgoQQ3VycmVuY3lFeGNoYW5nZRIKCgJpZBgBIAEoCRIRCgl0ZW5hbnRfaWQYAiABKAkSDwoHdXNlcl9pZBgDIAEoCRIlCgtmcm9tX2Ftb3VudBgEIAEoCzIQLmJ1ZGdldC52MS5Nb25leRIjCgl0b19hbW91bnQYBSABKAsyEC5idWRnZXQudjEuTW9uZXkSFAoMcmF0ZV9kZWNpbWFsGAYgASgJEi8KC29jY3VycmVkX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIMCgRub3RlGAggASgJEi4KCmNyZWF0ZWRfYXQYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIqoBCh1DcmVhdGVDdXJyZW5jeUV4Y2hhbmdlUmVxdWVzdBIlCgtmcm9tX2Ftb3VudBgBIAEoCzIQLmJ1ZGdldC52MS5Nb25leRIjCgl0b19hbW91bnQYAiABKAsyEC5idWRnZXQudjEuTW9uZXkSLwoLb2NjdXJyZWRfYXQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEgwKBG5vdGUYBCABKAkiTwoeQ3JlYXRlQ3VycmVuY3lFeGNoYW5nZVJlc3BvbnNlEi0KCGV4Y2hhbmdlGAEgASgLMhsuYnVkZ2V0LnYxLkN1cnJlbmN5RXhjaGFuZ2UiRAocTGlzdEN1cnJlbmN5RXhjaGFuZ2VzUmVxdWVzdBIkCgRwYWdlGAEgASgLMhYuYnVkZ2V0LnYxLlBhZ2VSZXF1ZXN0InYKHUxpc3RDdXJyZW5jeUV4Y2hhbmdlc1Jlc3BvbnNlEi4KCWV4Y2hhbmdlcxgBIAMoCzIbLmJ1ZGdldC52MS5DdXJyZW5jeUV4Y2hhbmdlEiUKBHBhZ2UYAiABKAsyFy5idWRnZXQudjEuUGFnZVJlc3BvbnNlIisKHURlbGV0ZUN1cnJlbmN5RXhjaGFuZ2VSZXF1ZXN0EgoKAmlkGAEgASgJIiAKHkRlbGV0ZUN1cnJlbmN5RXhjaGFuZ2VSZXNwb25zZTLjAgoXQ3VycmVuY3lFeGNoYW5nZVNlcnZpY2USbQoWQ3JlYXRlQ3VycmVuY3lFeGNoYW5nZRIoLmJ1ZGdldC52MS5DcmVhdGVDdXJyZW5jeUV4Y2hhbmdlUmVxdWVzdBopLmJ1ZGdldC52MS5DcmVhdGVDdXJyZW5jeUV4Y2hhbmdlUmVzcG9uc2USagoVTGlzdEN1cnJlbmN5RXhjaGFuZ2VzEicuYnVkZ2V0LnYxLkxpc3RDdXJyZW5jeUV4Y2hhbmdlc1JlcXVlc3QaKC5idWRnZXQudjEuTGlzdEN1cnJlbmN5RXhjaGFuZ2VzUmVzcG9uc2USbQoWRGVsZXRlQ3VycmVuY3lFeGNoYW5nZRIoLmJ1ZGdldC52MS5EZWxldGVDdXJyZW5jeUV4Y2hhbmdlUmVxdWVzdBopLmJ1ZGdldC52MS5EZWxldGVDdXJyZW5jeUV4Y2hhbmdlUmVzcG9uc2VCOFo2Z2l0aHViLmNvbS9wb3NpdHJvbjQ4L2J1ZGdldC9nZW4vZ28vYnVkZ2V0L3YxO2J1ZGdldHYxYgZwcm90bzM", [file_google_protobuf_timestamp, file_budget_v1_common]);

/**
 * @generated from message budget.v1.CurrencyExchange
 */
export type CurrencyExchange = Message<"budget.v1.CurrencyExchange"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string tenant_id = 2;
   */
  tenantId: string;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: budget.v1.Money from_amount = 4;
   */
  fromAmount?: Money;

  /**
   * @generated from field: budget.v1.Money to_amount = 5;
   */
  toAmount?: Money;

  /**
   * to_amount / from_amount
   *
   * @generated from field: string rate_decimal = 6;
   */
  rateDecimal: string;

  /**
   * @generated from field: google.protobuf.Timestamp occurred_at = 7;
   */
  occurredAt?: Timestamp;

  /**
   * @generated from field: string note = 8;
   */
  note: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message budget.v1.CurrencyExchange.
 * Use `create(CurrencyExchangeSchema)` to create a new message.
 */
export const CurrencyExchangeSchema: GenMessage<CurrencyExchange> = /*@__PURE__*/
  messageDesc(file_budget_v1_currency_exchange, 0);

/**
 * @generated from message budget.v1.CreateCurrencyExchangeRequest
 */
export type CreateCurrencyExchangeRequest = Message<"budget.v1.CreateCurrencyExchangeRequest"> & {
  /**
   * @generated from field: budget.v1.Money from_amount = 1;
   */
  fromAmount?: Money;

  /**
   * @generated from field: budget.v1.Money to_amount = 2;
   */
  toAmount?: Money;

  /**
   * @generated from field: google.protobuf.Timestamp occurred_at = 3;
   */
  occurredAt?: Timestamp;

  /**
   * @generated from field: string note = 4;
   */
  note: string;
};

/**
 * Describes the message budget.v1.CreateCurrencyExchangeRequest.
 * Use `create(CreateCurrencyExchangeRequestSchema)` to create a new message.
 */
export const CreateCurrencyExchangeRequestSchema: GenMessage<CreateCurrencyExchangeRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_currency_exchange, 1);

/**
 * @generated from message budget.v1.CreateCurrencyExchangeResponse
 */
export type CreateCurrencyExchangeResponse = Message<"budget.v1.CreateCurrencyExchangeResponse"> & {
  /**
   * @generated from field: budget.v1.CurrencyExchange exchange = 1;
   */
  exchange?: CurrencyExchange;
};

/**
 * Describes the message budget.v1.CreateCurrencyExchangeResponse.
 * Use `create(CreateCurrencyExchangeResponseSchema)` to create a new message.
 */
export const CreateCurrencyExchangeResponseSchema: GenMessage<CreateCurrencyExchangeResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_currency_exchange, 2);

/**
 * @generated from message budget.v1.ListCurrencyExchangesRequest
 */
export type ListCurrencyExchangesRequest = Message<"budget.v1.ListCurrencyExchangesRequest"> & {
  /**
   * @generated from field: budget.v1.PageRequest page = 1;
   */
  page?: PageRequest;
};

/**
 * Describes the message budget.v1.ListCurrencyExchangesRequest.
 * Use `create(ListCurrencyExchangesRequestSchema)` to create a new message.
 */
export const ListCurrencyExchangesRequestSchema: GenMessage<ListCurrencyExchangesRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_currency_exchange, 3);

/**
 * @generated from message budget.v1.ListCurrencyExchangesResponse
 */
export type ListCurrencyExchangesResponse = Message<"budget.v1.ListCurrencyExchangesResponse"> & {
  /**
   * @generated from field: repeated budget.v1.CurrencyExchange exchanges = 1;
   */
  exchanges: CurrencyExchange[];

  /**
   * @generated from field: budget.v1.PageResponse page = 2;
   */
  page?: PageResponse;
};

/**
 * Describes the message budget.v1.ListCurrencyExchangesResponse.
 * Use `create(ListCurrencyExchangesResponseSchema)` to create a new message.
 */
export const ListCurrencyExchangesResponseSchema: GenMessage<ListCurrencyExchangesResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_currency_exchange, 4);

/**
 * @generated from message budget.v1.DeleteCurrencyExchangeRequest
 */
export type DeleteCurrencyExchangeRequest = Message<"budget.v1.DeleteCurrencyExchangeRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message budget.v1.DeleteCurrencyExchangeRequest.
 * Use `create(DeleteCurrencyExchangeRequestSchema)` to create a new message.
 */
export const DeleteCurrencyExchangeRequestSchema: GenMessage<DeleteCurrencyExchangeRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_currency_exchange, 5);

/**
 * @generated from message budget.v1.DeleteCurrencyExchangeResponse
 */
export type DeleteCurrencyExchangeResponse = Message<"budget.v1.DeleteCurrencyExchangeResponse"> & {
};

/**
 * Describes the message budget.v1.DeleteCurrencyExchangeResponse.
 * Use `create(DeleteCurrencyExchangeResponseSchema)` to create a new message.
 */
export const DeleteCurrencyExchangeResponseSchema: GenMessage<DeleteCurrencyExchangeResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_currency_exchange, 6);

/**
 * @generated from service budget.v1.CurrencyExchangeService
 */
export const CurrencyExchangeService: GenService<{
  /**
   * @generated from rpc budget.v1.CurrencyExchangeService.CreateCurrencyExchange
   */
  createCurrencyExchange: {
    methodKind: "unary";
    input: typeof CreateCurrencyExchangeRequestSchema;
    output: typeof CreateCurrencyExchangeResponseSchema;
  },
  /**
   * @generated from rpc budget.v1.CurrencyExchangeService.ListCurrencyExchanges
   */
  listCurrencyExchanges: {
    methodKind: "unary";
    input: typeof ListCurrencyExchangesRequestSchema;
    output: typeof ListCurrencyExchangesResponseSchema;
  },
  /**
   * @generated from rpc budget.v1.CurrencyExchangeService.DeleteCurrencyExchange
   */
  deleteCurrencyExchange: {
    methodKind: "unary";
    input: typeof DeleteCurrencyExchangeRequestSchema;
    output: typeof DeleteCurrencyExchangeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_budget_v1_currency_exchange, 0);
