// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/fx.proto (package budget.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BatchGetRatesRequest, BatchGetRatesResponse, GetRateRequest, GetRateResponse, UpsertRateRequest, UpsertRateResponse } from "./fx_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service budget.v1.FxService
 */
export const FxService = {
  typeName: "budget.v1.FxService",
  methods: {
    /**
     * Returns a rate from one currency to another as of date
     *
     * @generated from rpc budget.v1.FxService.GetRate
     */
    getRate: {
      name: "GetRate",
      I: GetRateRequest,
      O: GetRateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Administrative/manual override of a rate
     *
     * @generated from rpc budget.v1.FxService.UpsertRate
     */
    upsertRate: {
      name: "UpsertRate",
      I: UpsertRateRequest,
      O: UpsertRateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Batch query for multiple currencies to the same target
     *
     * @generated from rpc budget.v1.FxService.BatchGetRates
     */
    batchGetRates: {
      name: "BatchGetRates",
      I: BatchGetRatesRequest,
      O: BatchGetRatesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

