// @generated by protoc-gen-es v2.8.0 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/fx.proto (package budget.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file budget/v1/fx.proto.
 */
export const file_budget_v1_fx: GenFile = /*@__PURE__*/
  fileDesc("ChJidWRnZXQvdjEvZngucHJvdG8SCWJ1ZGdldC52MSKRAQoGRnhSYXRlEhoKEmZyb21fY3VycmVuY3lfY29kZRgBIAEoCRIYChB0b19jdXJyZW5jeV9jb2RlGAIgASgJEhQKDHJhdGVfZGVjaW1hbBgDIAEoCRIpCgVhc19vZhgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEAoIcHJvdmlkZXIYBSABKAkicQoOR2V0UmF0ZVJlcXVlc3QSGgoSZnJvbV9jdXJyZW5jeV9jb2RlGAEgASgJEhgKEHRvX2N1cnJlbmN5X2NvZGUYAiABKAkSKQoFYXNfb2YYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIjIKD0dldFJhdGVSZXNwb25zZRIfCgRyYXRlGAEgASgLMhEuYnVkZ2V0LnYxLkZ4UmF0ZSI0ChFVcHNlcnRSYXRlUmVxdWVzdBIfCgRyYXRlGAEgASgLMhEuYnVkZ2V0LnYxLkZ4UmF0ZSI1ChJVcHNlcnRSYXRlUmVzcG9uc2USHwoEcmF0ZRgBIAEoCzIRLmJ1ZGdldC52MS5GeFJhdGUieAoUQmF0Y2hHZXRSYXRlc1JlcXVlc3QSGwoTZnJvbV9jdXJyZW5jeV9jb2RlcxgBIAMoCRIYChB0b19jdXJyZW5jeV9jb2RlGAIgASgJEikKBWFzX29mGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCI5ChVCYXRjaEdldFJhdGVzUmVzcG9uc2USIAoFcmF0ZXMYASADKAsyES5idWRnZXQudjEuRnhSYXRlMuwBCglGeFNlcnZpY2USQAoHR2V0UmF0ZRIZLmJ1ZGdldC52MS5HZXRSYXRlUmVxdWVzdBoaLmJ1ZGdldC52MS5HZXRSYXRlUmVzcG9uc2USSQoKVXBzZXJ0UmF0ZRIcLmJ1ZGdldC52MS5VcHNlcnRSYXRlUmVxdWVzdBodLmJ1ZGdldC52MS5VcHNlcnRSYXRlUmVzcG9uc2USUgoNQmF0Y2hHZXRSYXRlcxIfLmJ1ZGdldC52MS5CYXRjaEdldFJhdGVzUmVxdWVzdBogLmJ1ZGdldC52MS5CYXRjaEdldFJhdGVzUmVzcG9uc2VCOFo2Z2l0aHViLmNvbS9wb3NpdHJvbjQ4L2J1ZGdldC9nZW4vZ28vYnVkZ2V0L3YxO2J1ZGdldHYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Represents a single FX rate quote (from → to) as of specific date/time
 *
 * @generated from message budget.v1.FxRate
 */
export type FxRate = Message<"budget.v1.FxRate"> & {
  /**
   * e.g. "USD"
   *
   * @generated from field: string from_currency_code = 1;
   */
  fromCurrencyCode: string;

  /**
   * e.g. "RUB"
   *
   * @generated from field: string to_currency_code = 2;
   */
  toCurrencyCode: string;

  /**
   * e.g. "92.3456"
   *
   * @generated from field: string rate_decimal = 3;
   */
  rateDecimal: string;

  /**
   * @generated from field: google.protobuf.Timestamp as_of = 4;
   */
  asOf?: Timestamp;

  /**
   * e.g. "ecb", "cbr", "manual"
   *
   * @generated from field: string provider = 5;
   */
  provider: string;
};

/**
 * Describes the message budget.v1.FxRate.
 * Use `create(FxRateSchema)` to create a new message.
 */
export const FxRateSchema: GenMessage<FxRate> = /*@__PURE__*/
  messageDesc(file_budget_v1_fx, 0);

/**
 * @generated from message budget.v1.GetRateRequest
 */
export type GetRateRequest = Message<"budget.v1.GetRateRequest"> & {
  /**
   * @generated from field: string from_currency_code = 1;
   */
  fromCurrencyCode: string;

  /**
   * @generated from field: string to_currency_code = 2;
   */
  toCurrencyCode: string;

  /**
   * date at which to get the rate (truncate to day server-side if needed)
   *
   * @generated from field: google.protobuf.Timestamp as_of = 3;
   */
  asOf?: Timestamp;
};

/**
 * Describes the message budget.v1.GetRateRequest.
 * Use `create(GetRateRequestSchema)` to create a new message.
 */
export const GetRateRequestSchema: GenMessage<GetRateRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_fx, 1);

/**
 * @generated from message budget.v1.GetRateResponse
 */
export type GetRateResponse = Message<"budget.v1.GetRateResponse"> & {
  /**
   * @generated from field: budget.v1.FxRate rate = 1;
   */
  rate?: FxRate;
};

/**
 * Describes the message budget.v1.GetRateResponse.
 * Use `create(GetRateResponseSchema)` to create a new message.
 */
export const GetRateResponseSchema: GenMessage<GetRateResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_fx, 2);

/**
 * @generated from message budget.v1.UpsertRateRequest
 */
export type UpsertRateRequest = Message<"budget.v1.UpsertRateRequest"> & {
  /**
   * @generated from field: budget.v1.FxRate rate = 1;
   */
  rate?: FxRate;
};

/**
 * Describes the message budget.v1.UpsertRateRequest.
 * Use `create(UpsertRateRequestSchema)` to create a new message.
 */
export const UpsertRateRequestSchema: GenMessage<UpsertRateRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_fx, 3);

/**
 * @generated from message budget.v1.UpsertRateResponse
 */
export type UpsertRateResponse = Message<"budget.v1.UpsertRateResponse"> & {
  /**
   * @generated from field: budget.v1.FxRate rate = 1;
   */
  rate?: FxRate;
};

/**
 * Describes the message budget.v1.UpsertRateResponse.
 * Use `create(UpsertRateResponseSchema)` to create a new message.
 */
export const UpsertRateResponseSchema: GenMessage<UpsertRateResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_fx, 4);

/**
 * @generated from message budget.v1.BatchGetRatesRequest
 */
export type BatchGetRatesRequest = Message<"budget.v1.BatchGetRatesRequest"> & {
  /**
   * @generated from field: repeated string from_currency_codes = 1;
   */
  fromCurrencyCodes: string[];

  /**
   * @generated from field: string to_currency_code = 2;
   */
  toCurrencyCode: string;

  /**
   * @generated from field: google.protobuf.Timestamp as_of = 3;
   */
  asOf?: Timestamp;
};

/**
 * Describes the message budget.v1.BatchGetRatesRequest.
 * Use `create(BatchGetRatesRequestSchema)` to create a new message.
 */
export const BatchGetRatesRequestSchema: GenMessage<BatchGetRatesRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_fx, 5);

/**
 * @generated from message budget.v1.BatchGetRatesResponse
 */
export type BatchGetRatesResponse = Message<"budget.v1.BatchGetRatesResponse"> & {
  /**
   * @generated from field: repeated budget.v1.FxRate rates = 1;
   */
  rates: FxRate[];
};

/**
 * Describes the message budget.v1.BatchGetRatesResponse.
 * Use `create(BatchGetRatesResponseSchema)` to create a new message.
 */
export const BatchGetRatesResponseSchema: GenMessage<BatchGetRatesResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_fx, 6);

/**
 * @generated from service budget.v1.FxService
 */
export const FxService: GenService<{
  /**
   * Returns a rate from one currency to another as of date
   *
   * @generated from rpc budget.v1.FxService.GetRate
   */
  getRate: {
    methodKind: "unary";
    input: typeof GetRateRequestSchema;
    output: typeof GetRateResponseSchema;
  },
  /**
   * Administrative/manual override of a rate
   *
   * @generated from rpc budget.v1.FxService.UpsertRate
   */
  upsertRate: {
    methodKind: "unary";
    input: typeof UpsertRateRequestSchema;
    output: typeof UpsertRateResponseSchema;
  },
  /**
   * Batch query for multiple currencies to the same target
   *
   * @generated from rpc budget.v1.FxService.BatchGetRates
   */
  batchGetRates: {
    methodKind: "unary";
    input: typeof BatchGetRatesRequestSchema;
    output: typeof BatchGetRatesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_budget_v1_fx, 0);

