// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/import.proto (package budget.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CommitCsvImportRequest, CommitCsvImportResponse, ConfigureCsvMappingRequest, ConfigureCsvMappingResponse, PreviewCsvImportRequest, PreviewCsvImportResponse, StartCsvImportRequest, StartCsvImportResponse, UploadCsvChunkRequest, UploadCsvChunkResponse } from "./import_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service budget.v1.ImportService
 */
export const ImportService = {
  typeName: "budget.v1.ImportService",
  methods: {
    /**
     * @generated from rpc budget.v1.ImportService.StartCsvImport
     */
    startCsvImport: {
      name: "StartCsvImport",
      I: StartCsvImportRequest,
      O: StartCsvImportResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.ImportService.UploadCsvChunk
     */
    uploadCsvChunk: {
      name: "UploadCsvChunk",
      I: UploadCsvChunkRequest,
      O: UploadCsvChunkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.ImportService.ConfigureCsvMapping
     */
    configureCsvMapping: {
      name: "ConfigureCsvMapping",
      I: ConfigureCsvMappingRequest,
      O: ConfigureCsvMappingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.ImportService.PreviewCsvImport
     */
    previewCsvImport: {
      name: "PreviewCsvImport",
      I: PreviewCsvImportRequest,
      O: PreviewCsvImportResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.ImportService.CommitCsvImport
     */
    commitCsvImport: {
      name: "CommitCsvImport",
      I: CommitCsvImportRequest,
      O: CommitCsvImportResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

