// @generated by protoc-gen-es v2.6.3 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/import.proto (package budget.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file budget/v1/import.proto.
 */
export const file_budget_v1_import: GenFile = /*@__PURE__*/
  fileDesc("ChZidWRnZXQvdjEvaW1wb3J0LnByb3RvEglidWRnZXQudjEiXQoVU3RhcnRDc3ZJbXBvcnRSZXF1ZXN0EhAKCGZpbGVuYW1lGAEgASgJEhEKCWRlbGltaXRlchgCIAEoCRINCgVxdW90ZRgDIAEoCRIQCghlbmNvZGluZxgEIAEoCSIrChZTdGFydENzdkltcG9ydFJlc3BvbnNlEhEKCWltcG9ydF9pZBgBIAEoCSJHChVVcGxvYWRDc3ZDaHVua1JlcXVlc3QSEQoJaW1wb3J0X2lkGAEgASgJEg0KBWNodW5rGAIgASgMEgwKBGxhc3QYAyABKAgiMAoWVXBsb2FkQ3N2Q2h1bmtSZXNwb25zZRIWCg5yZWNlaXZlZF9ieXRlcxgBIAEoAyKiAQoQQ3N2Q29sdW1uTWFwcGluZxITCgtkYXRlX2NvbHVtbhgBIAEoCRIVCg1hbW91bnRfY29sdW1uGAIgASgJEhwKFGN1cnJlbmN5X2NvZGVfY29sdW1uGAMgASgJEhMKC3R5cGVfY29sdW1uGAQgASgJEhcKD2NhdGVnb3J5X2NvbHVtbhgFIAEoCRIWCg5jb21tZW50X2NvbHVtbhgGIAEoCSJdChpDb25maWd1cmVDc3ZNYXBwaW5nUmVxdWVzdBIRCglpbXBvcnRfaWQYASABKAkSLAoHbWFwcGluZxgCIAEoCzIbLmJ1ZGdldC52MS5Dc3ZDb2x1bW5NYXBwaW5nIh0KG0NvbmZpZ3VyZUNzdk1hcHBpbmdSZXNwb25zZSI7ChdQcmV2aWV3Q3N2SW1wb3J0UmVxdWVzdBIRCglpbXBvcnRfaWQYASABKAkSDQoFbGltaXQYAiABKAUiWAoYUHJldmlld0NzdkltcG9ydFJlc3BvbnNlEhIKCnRvdGFsX3Jvd3MYASABKAUSEgoKdmFsaWRfcm93cxgCIAEoBRIUCgxpbnZhbGlkX3Jvd3MYAyABKAUiPAoWQ29tbWl0Q3N2SW1wb3J0UmVxdWVzdBIRCglpbXBvcnRfaWQYASABKAkSDwoHZHJ5X3J1bhgCIAEoCCI7ChdDb21taXRDc3ZJbXBvcnRSZXNwb25zZRIQCghpbnNlcnRlZBgBIAEoBRIOCgZmYWlsZWQYAiABKAUy2gMKDUltcG9ydFNlcnZpY2USVQoOU3RhcnRDc3ZJbXBvcnQSIC5idWRnZXQudjEuU3RhcnRDc3ZJbXBvcnRSZXF1ZXN0GiEuYnVkZ2V0LnYxLlN0YXJ0Q3N2SW1wb3J0UmVzcG9uc2USVQoOVXBsb2FkQ3N2Q2h1bmsSIC5idWRnZXQudjEuVXBsb2FkQ3N2Q2h1bmtSZXF1ZXN0GiEuYnVkZ2V0LnYxLlVwbG9hZENzdkNodW5rUmVzcG9uc2USZAoTQ29uZmlndXJlQ3N2TWFwcGluZxIlLmJ1ZGdldC52MS5Db25maWd1cmVDc3ZNYXBwaW5nUmVxdWVzdBomLmJ1ZGdldC52MS5Db25maWd1cmVDc3ZNYXBwaW5nUmVzcG9uc2USWwoQUHJldmlld0NzdkltcG9ydBIiLmJ1ZGdldC52MS5QcmV2aWV3Q3N2SW1wb3J0UmVxdWVzdBojLmJ1ZGdldC52MS5QcmV2aWV3Q3N2SW1wb3J0UmVzcG9uc2USWAoPQ29tbWl0Q3N2SW1wb3J0EiEuYnVkZ2V0LnYxLkNvbW1pdENzdkltcG9ydFJlcXVlc3QaIi5idWRnZXQudjEuQ29tbWl0Q3N2SW1wb3J0UmVzcG9uc2VCOFo2Z2l0aHViLmNvbS9wb3NpdHJvbjQ4L2J1ZGdldC9nZW4vZ28vYnVkZ2V0L3YxO2J1ZGdldHYxYgZwcm90bzM");

/**
 * @generated from message budget.v1.StartCsvImportRequest
 */
export type StartCsvImportRequest = Message<"budget.v1.StartCsvImportRequest"> & {
  /**
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * default ","
   *
   * @generated from field: string delimiter = 2;
   */
  delimiter: string;

  /**
   * default '"'
   *
   * @generated from field: string quote = 3;
   */
  quote: string;

  /**
   * default "utf-8"
   *
   * @generated from field: string encoding = 4;
   */
  encoding: string;
};

/**
 * Describes the message budget.v1.StartCsvImportRequest.
 * Use `create(StartCsvImportRequestSchema)` to create a new message.
 */
export const StartCsvImportRequestSchema: GenMessage<StartCsvImportRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_import, 0);

/**
 * @generated from message budget.v1.StartCsvImportResponse
 */
export type StartCsvImportResponse = Message<"budget.v1.StartCsvImportResponse"> & {
  /**
   * @generated from field: string import_id = 1;
   */
  importId: string;
};

/**
 * Describes the message budget.v1.StartCsvImportResponse.
 * Use `create(StartCsvImportResponseSchema)` to create a new message.
 */
export const StartCsvImportResponseSchema: GenMessage<StartCsvImportResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_import, 1);

/**
 * @generated from message budget.v1.UploadCsvChunkRequest
 */
export type UploadCsvChunkRequest = Message<"budget.v1.UploadCsvChunkRequest"> & {
  /**
   * @generated from field: string import_id = 1;
   */
  importId: string;

  /**
   * @generated from field: bytes chunk = 2;
   */
  chunk: Uint8Array;

  /**
   * @generated from field: bool last = 3;
   */
  last: boolean;
};

/**
 * Describes the message budget.v1.UploadCsvChunkRequest.
 * Use `create(UploadCsvChunkRequestSchema)` to create a new message.
 */
export const UploadCsvChunkRequestSchema: GenMessage<UploadCsvChunkRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_import, 2);

/**
 * @generated from message budget.v1.UploadCsvChunkResponse
 */
export type UploadCsvChunkResponse = Message<"budget.v1.UploadCsvChunkResponse"> & {
  /**
   * @generated from field: int64 received_bytes = 1;
   */
  receivedBytes: bigint;
};

/**
 * Describes the message budget.v1.UploadCsvChunkResponse.
 * Use `create(UploadCsvChunkResponseSchema)` to create a new message.
 */
export const UploadCsvChunkResponseSchema: GenMessage<UploadCsvChunkResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_import, 3);

/**
 * @generated from message budget.v1.CsvColumnMapping
 */
export type CsvColumnMapping = Message<"budget.v1.CsvColumnMapping"> & {
  /**
   * @generated from field: string date_column = 1;
   */
  dateColumn: string;

  /**
   * @generated from field: string amount_column = 2;
   */
  amountColumn: string;

  /**
   * optional
   *
   * @generated from field: string currency_code_column = 3;
   */
  currencyCodeColumn: string;

  /**
   * income/expense or signed amounts
   *
   * @generated from field: string type_column = 4;
   */
  typeColumn: string;

  /**
   * to map names → category_ids
   *
   * @generated from field: string category_column = 5;
   */
  categoryColumn: string;

  /**
   * @generated from field: string comment_column = 6;
   */
  commentColumn: string;
};

/**
 * Describes the message budget.v1.CsvColumnMapping.
 * Use `create(CsvColumnMappingSchema)` to create a new message.
 */
export const CsvColumnMappingSchema: GenMessage<CsvColumnMapping> = /*@__PURE__*/
  messageDesc(file_budget_v1_import, 4);

/**
 * @generated from message budget.v1.ConfigureCsvMappingRequest
 */
export type ConfigureCsvMappingRequest = Message<"budget.v1.ConfigureCsvMappingRequest"> & {
  /**
   * @generated from field: string import_id = 1;
   */
  importId: string;

  /**
   * @generated from field: budget.v1.CsvColumnMapping mapping = 2;
   */
  mapping?: CsvColumnMapping;
};

/**
 * Describes the message budget.v1.ConfigureCsvMappingRequest.
 * Use `create(ConfigureCsvMappingRequestSchema)` to create a new message.
 */
export const ConfigureCsvMappingRequestSchema: GenMessage<ConfigureCsvMappingRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_import, 5);

/**
 * @generated from message budget.v1.ConfigureCsvMappingResponse
 */
export type ConfigureCsvMappingResponse = Message<"budget.v1.ConfigureCsvMappingResponse"> & {
};

/**
 * Describes the message budget.v1.ConfigureCsvMappingResponse.
 * Use `create(ConfigureCsvMappingResponseSchema)` to create a new message.
 */
export const ConfigureCsvMappingResponseSchema: GenMessage<ConfigureCsvMappingResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_import, 6);

/**
 * @generated from message budget.v1.PreviewCsvImportRequest
 */
export type PreviewCsvImportRequest = Message<"budget.v1.PreviewCsvImportRequest"> & {
  /**
   * @generated from field: string import_id = 1;
   */
  importId: string;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;
};

/**
 * Describes the message budget.v1.PreviewCsvImportRequest.
 * Use `create(PreviewCsvImportRequestSchema)` to create a new message.
 */
export const PreviewCsvImportRequestSchema: GenMessage<PreviewCsvImportRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_import, 7);

/**
 * @generated from message budget.v1.PreviewCsvImportResponse
 */
export type PreviewCsvImportResponse = Message<"budget.v1.PreviewCsvImportResponse"> & {
  /**
   * @generated from field: int32 total_rows = 1;
   */
  totalRows: number;

  /**
   * @generated from field: int32 valid_rows = 2;
   */
  validRows: number;

  /**
   * @generated from field: int32 invalid_rows = 3;
   */
  invalidRows: number;
};

/**
 * Describes the message budget.v1.PreviewCsvImportResponse.
 * Use `create(PreviewCsvImportResponseSchema)` to create a new message.
 */
export const PreviewCsvImportResponseSchema: GenMessage<PreviewCsvImportResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_import, 8);

/**
 * @generated from message budget.v1.CommitCsvImportRequest
 */
export type CommitCsvImportRequest = Message<"budget.v1.CommitCsvImportRequest"> & {
  /**
   * @generated from field: string import_id = 1;
   */
  importId: string;

  /**
   * @generated from field: bool dry_run = 2;
   */
  dryRun: boolean;
};

/**
 * Describes the message budget.v1.CommitCsvImportRequest.
 * Use `create(CommitCsvImportRequestSchema)` to create a new message.
 */
export const CommitCsvImportRequestSchema: GenMessage<CommitCsvImportRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_import, 9);

/**
 * @generated from message budget.v1.CommitCsvImportResponse
 */
export type CommitCsvImportResponse = Message<"budget.v1.CommitCsvImportResponse"> & {
  /**
   * @generated from field: int32 inserted = 1;
   */
  inserted: number;

  /**
   * @generated from field: int32 failed = 2;
   */
  failed: number;
};

/**
 * Describes the message budget.v1.CommitCsvImportResponse.
 * Use `create(CommitCsvImportResponseSchema)` to create a new message.
 */
export const CommitCsvImportResponseSchema: GenMessage<CommitCsvImportResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_import, 10);

/**
 * @generated from service budget.v1.ImportService
 */
export const ImportService: GenService<{
  /**
   * @generated from rpc budget.v1.ImportService.StartCsvImport
   */
  startCsvImport: {
    methodKind: "unary";
    input: typeof StartCsvImportRequestSchema;
    output: typeof StartCsvImportResponseSchema;
  },
  /**
   * @generated from rpc budget.v1.ImportService.UploadCsvChunk
   */
  uploadCsvChunk: {
    methodKind: "unary";
    input: typeof UploadCsvChunkRequestSchema;
    output: typeof UploadCsvChunkResponseSchema;
  },
  /**
   * @generated from rpc budget.v1.ImportService.ConfigureCsvMapping
   */
  configureCsvMapping: {
    methodKind: "unary";
    input: typeof ConfigureCsvMappingRequestSchema;
    output: typeof ConfigureCsvMappingResponseSchema;
  },
  /**
   * @generated from rpc budget.v1.ImportService.PreviewCsvImport
   */
  previewCsvImport: {
    methodKind: "unary";
    input: typeof PreviewCsvImportRequestSchema;
    output: typeof PreviewCsvImportResponseSchema;
  },
  /**
   * @generated from rpc budget.v1.ImportService.CommitCsvImport
   */
  commitCsvImport: {
    methodKind: "unary";
    input: typeof CommitCsvImportRequestSchema;
    output: typeof CommitCsvImportResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_budget_v1_import, 0);

