// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/oauth.proto (package budget.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelAuthRequest, CancelAuthResponse, GenerateAuthLinkRequest, GenerateAuthLinkResponse, GetAuthLogsRequest, GetAuthLogsResponse, GetAuthStatusRequest, GetAuthStatusResponse, GetTelegramSessionRequest, GetTelegramSessionResponse, GetVerificationCodeRequest, GetVerificationCodeResponse, ListTelegramSessionsRequest, ListTelegramSessionsResponse, RevokeTelegramSessionRequest, RevokeTelegramSessionResponse, VerifyAuthCodeRequest, VerifyAuthCodeResponse } from "./oauth_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service budget.v1.OAuthService
 */
export const OAuthService = {
  typeName: "budget.v1.OAuthService",
  methods: {
    /**
     * Основные методы OAuth2 flow
     *
     * @generated from rpc budget.v1.OAuthService.GenerateAuthLink
     */
    generateAuthLink: {
      name: "GenerateAuthLink",
      I: GenerateAuthLinkRequest,
      O: GenerateAuthLinkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.OAuthService.GetVerificationCode
     */
    getVerificationCode: {
      name: "GetVerificationCode",
      I: GetVerificationCodeRequest,
      O: GetVerificationCodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.OAuthService.VerifyAuthCode
     */
    verifyAuthCode: {
      name: "VerifyAuthCode",
      I: VerifyAuthCodeRequest,
      O: VerifyAuthCodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.OAuthService.CancelAuth
     */
    cancelAuth: {
      name: "CancelAuth",
      I: CancelAuthRequest,
      O: CancelAuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.OAuthService.GetAuthStatus
     */
    getAuthStatus: {
      name: "GetAuthStatus",
      I: GetAuthStatusRequest,
      O: GetAuthStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Управление сессиями Telegram
     *
     * @generated from rpc budget.v1.OAuthService.GetTelegramSession
     */
    getTelegramSession: {
      name: "GetTelegramSession",
      I: GetTelegramSessionRequest,
      O: GetTelegramSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.OAuthService.RevokeTelegramSession
     */
    revokeTelegramSession: {
      name: "RevokeTelegramSession",
      I: RevokeTelegramSessionRequest,
      O: RevokeTelegramSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.OAuthService.ListTelegramSessions
     */
    listTelegramSessions: {
      name: "ListTelegramSessions",
      I: ListTelegramSessionsRequest,
      O: ListTelegramSessionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Логирование безопасности
     *
     * @generated from rpc budget.v1.OAuthService.GetAuthLogs
     */
    getAuthLogs: {
      name: "GetAuthLogs",
      I: GetAuthLogsRequest,
      O: GetAuthLogsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

