// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/report.proto (package budget.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetMonthlySummaryRequest, GetMonthlySummaryResponse } from "./report_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service budget.v1.ReportService
 */
export const ReportService = {
  typeName: "budget.v1.ReportService",
  methods: {
    /**
     * @generated from rpc budget.v1.ReportService.GetMonthlySummary
     */
    getMonthlySummary: {
      name: "GetMonthlySummary",
      I: GetMonthlySummaryRequest,
      O: GetMonthlySummaryResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

