// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file budget/v1/report.proto (package budget.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Money, TransactionType } from "./common_pb";
import { file_budget_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file budget/v1/report.proto.
 */
export const file_budget_v1_report: GenFile = /*@__PURE__*/
  fileDesc("ChZidWRnZXQvdjEvcmVwb3J0LnByb3RvEglidWRnZXQudjEikwEKGk1vbnRobHlDYXRlZ29yeVN1bW1hcnlJdGVtEhMKC2NhdGVnb3J5X2lkGAEgASgJEhUKDWNhdGVnb3J5X25hbWUYAiABKAkSKAoEdHlwZRgDIAEoDjIaLmJ1ZGdldC52MS5UcmFuc2FjdGlvblR5cGUSHwoFdG90YWwYBCABKAsyEC5idWRnZXQudjEuTW9uZXkihgEKGEdldE1vbnRobHlTdW1tYXJ5UmVxdWVzdBIMCgR5ZWFyGAEgASgFEg0KBW1vbnRoGAIgASgFEg4KBmxvY2FsZRgDIAEoCRIcChR0YXJnZXRfY3VycmVuY3lfY29kZRgEIAEoCRIfChd0aW1lem9uZV9vZmZzZXRfbWludXRlcxgFIAEoBSKiAQoZR2V0TW9udGhseVN1bW1hcnlSZXNwb25zZRI0CgVpdGVtcxgBIAMoCzIlLmJ1ZGdldC52MS5Nb250aGx5Q2F0ZWdvcnlTdW1tYXJ5SXRlbRImCgx0b3RhbF9pbmNvbWUYAiABKAsyEC5idWRnZXQudjEuTW9uZXkSJwoNdG90YWxfZXhwZW5zZRgDIAEoCzIQLmJ1ZGdldC52MS5Nb25leTJvCg1SZXBvcnRTZXJ2aWNlEl4KEUdldE1vbnRobHlTdW1tYXJ5EiMuYnVkZ2V0LnYxLkdldE1vbnRobHlTdW1tYXJ5UmVxdWVzdBokLmJ1ZGdldC52MS5HZXRNb250aGx5U3VtbWFyeVJlc3BvbnNlQjhaNmdpdGh1Yi5jb20vcG9zaXRyb240OC9idWRnZXQvZ2VuL2dvL2J1ZGdldC92MTtidWRnZXR2MWIGcHJvdG8z", [file_budget_v1_common]);

/**
 * @generated from message budget.v1.MonthlyCategorySummaryItem
 */
export type MonthlyCategorySummaryItem = Message<"budget.v1.MonthlyCategorySummaryItem"> & {
  /**
   * @generated from field: string category_id = 1;
   */
  categoryId: string;

  /**
   * localized best-effort
   *
   * @generated from field: string category_name = 2;
   */
  categoryName: string;

  /**
   * income / expense
   *
   * @generated from field: budget.v1.TransactionType type = 3;
   */
  type: TransactionType;

  /**
   * in target currency
   *
   * @generated from field: budget.v1.Money total = 4;
   */
  total?: Money;
};

/**
 * Describes the message budget.v1.MonthlyCategorySummaryItem.
 * Use `create(MonthlyCategorySummaryItemSchema)` to create a new message.
 */
export const MonthlyCategorySummaryItemSchema: GenMessage<MonthlyCategorySummaryItem> = /*@__PURE__*/
  messageDesc(file_budget_v1_report, 0);

/**
 * @generated from message budget.v1.GetMonthlySummaryRequest
 */
export type GetMonthlySummaryRequest = Message<"budget.v1.GetMonthlySummaryRequest"> & {
  /**
   * e.g., 2025
   *
   * @generated from field: int32 year = 1;
   */
  year: number;

  /**
   * 1..12
   *
   * @generated from field: int32 month = 2;
   */
  month: number;

  /**
   * preferred translation
   *
   * @generated from field: string locale = 3;
   */
  locale: string;

  /**
   * if empty, use tenant default currency
   *
   * @generated from field: string target_currency_code = 4;
   */
  targetCurrencyCode: string;

  /**
   * minutes to add to local time to get UTC (JS getTimezoneOffset)
   *
   * @generated from field: int32 timezone_offset_minutes = 5;
   */
  timezoneOffsetMinutes: number;
};

/**
 * Describes the message budget.v1.GetMonthlySummaryRequest.
 * Use `create(GetMonthlySummaryRequestSchema)` to create a new message.
 */
export const GetMonthlySummaryRequestSchema: GenMessage<GetMonthlySummaryRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_report, 1);

/**
 * @generated from message budget.v1.GetMonthlySummaryResponse
 */
export type GetMonthlySummaryResponse = Message<"budget.v1.GetMonthlySummaryResponse"> & {
  /**
   * @generated from field: repeated budget.v1.MonthlyCategorySummaryItem items = 1;
   */
  items: MonthlyCategorySummaryItem[];

  /**
   * in target currency
   *
   * @generated from field: budget.v1.Money total_income = 2;
   */
  totalIncome?: Money;

  /**
   * in target currency
   *
   * @generated from field: budget.v1.Money total_expense = 3;
   */
  totalExpense?: Money;
};

/**
 * Describes the message budget.v1.GetMonthlySummaryResponse.
 * Use `create(GetMonthlySummaryResponseSchema)` to create a new message.
 */
export const GetMonthlySummaryResponseSchema: GenMessage<GetMonthlySummaryResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_report, 2);

/**
 * @generated from service budget.v1.ReportService
 */
export const ReportService: GenService<{
  /**
   * @generated from rpc budget.v1.ReportService.GetMonthlySummary
   */
  getMonthlySummary: {
    methodKind: "unary";
    input: typeof GetMonthlySummaryRequestSchema;
    output: typeof GetMonthlySummaryResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_budget_v1_report, 0);

