// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/tenant.proto (package budget.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddMemberRequest, AddMemberResponse, CreateTenantRequest, CreateTenantResponse, ListMembersRequest, ListMembersResponse, ListMyTenantsRequest, ListMyTenantsResponse, RemoveMemberRequest, RemoveMemberResponse, UpdateMemberRoleRequest, UpdateMemberRoleResponse, UpdateTenantRequest, UpdateTenantResponse } from "./tenant_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service budget.v1.TenantService
 */
export const TenantService = {
  typeName: "budget.v1.TenantService",
  methods: {
    /**
     * @generated from rpc budget.v1.TenantService.CreateTenant
     */
    createTenant: {
      name: "CreateTenant",
      I: CreateTenantRequest,
      O: CreateTenantResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.TenantService.ListMyTenants
     */
    listMyTenants: {
      name: "ListMyTenants",
      I: ListMyTenantsRequest,
      O: ListMyTenantsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.TenantService.UpdateTenant
     */
    updateTenant: {
      name: "UpdateTenant",
      I: UpdateTenantRequest,
      O: UpdateTenantResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.TenantService.ListMembers
     */
    listMembers: {
      name: "ListMembers",
      I: ListMembersRequest,
      O: ListMembersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.TenantService.AddMember
     */
    addMember: {
      name: "AddMember",
      I: AddMemberRequest,
      O: AddMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.TenantService.UpdateMemberRole
     */
    updateMemberRole: {
      name: "UpdateMemberRole",
      I: UpdateMemberRoleRequest,
      O: UpdateMemberRoleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.TenantService.RemoveMember
     */
    removeMember: {
      name: "RemoveMember",
      I: RemoveMemberRequest,
      O: RemoveMemberResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

