// @generated by protoc-gen-es v2.6.3 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/tenant.proto (package budget.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file budget/v1/tenant.proto.
 */
export const file_budget_v1_tenant: GenFile = /*@__PURE__*/
  fileDesc("ChZidWRnZXQvdjEvdGVuYW50LnByb3RvEglidWRnZXQudjEifwoGVGVuYW50EgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSDAoEc2x1ZxgDIAEoCRIdChVkZWZhdWx0X2N1cnJlbmN5X2NvZGUYBCABKAkSLgoKY3JlYXRlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAibgoQVGVuYW50TWVtYmVyc2hpcBIhCgZ0ZW5hbnQYASABKAsyES5idWRnZXQudjEuVGVuYW50EiMKBHJvbGUYAiABKA4yFS5idWRnZXQudjEuVGVuYW50Um9sZRISCgppc19kZWZhdWx0GAMgASgIIlAKE0NyZWF0ZVRlbmFudFJlcXVlc3QSDAoEbmFtZRgBIAEoCRIMCgRzbHVnGAIgASgJEh0KFWRlZmF1bHRfY3VycmVuY3lfY29kZRgDIAEoCSI5ChRDcmVhdGVUZW5hbnRSZXNwb25zZRIhCgZ0ZW5hbnQYASABKAsyES5idWRnZXQudjEuVGVuYW50IhYKFExpc3RNeVRlbmFudHNSZXF1ZXN0IkkKFUxpc3RNeVRlbmFudHNSZXNwb25zZRIwCgttZW1iZXJzaGlwcxgBIAMoCzIbLmJ1ZGdldC52MS5UZW5hbnRNZW1iZXJzaGlwKm8KClRlbmFudFJvbGUSGwoXVEVOQU5UX1JPTEVfVU5TUEVDSUZJRUQQABIVChFURU5BTlRfUk9MRV9PV05FUhABEhUKEVRFTkFOVF9ST0xFX0FETUlOEAISFgoSVEVOQU5UX1JPTEVfTUVNQkVSEAMytAEKDVRlbmFudFNlcnZpY2USTwoMQ3JlYXRlVGVuYW50Eh4uYnVkZ2V0LnYxLkNyZWF0ZVRlbmFudFJlcXVlc3QaHy5idWRnZXQudjEuQ3JlYXRlVGVuYW50UmVzcG9uc2USUgoNTGlzdE15VGVuYW50cxIfLmJ1ZGdldC52MS5MaXN0TXlUZW5hbnRzUmVxdWVzdBogLmJ1ZGdldC52MS5MaXN0TXlUZW5hbnRzUmVzcG9uc2VCOFo2Z2l0aHViLmNvbS9wb3NpdHJvbjQ4L2J1ZGdldC9nZW4vZ28vYnVkZ2V0L3YxO2J1ZGdldHYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message budget.v1.Tenant
 */
export type Tenant = Message<"budget.v1.Tenant"> & {
  /**
   * UUID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Display name
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * URL-friendly identifier
   *
   * @generated from field: string slug = 3;
   */
  slug: string;

  /**
   * e.g. "USD", "RUB"
   *
   * @generated from field: string default_currency_code = 4;
   */
  defaultCurrencyCode: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message budget.v1.Tenant.
 * Use `create(TenantSchema)` to create a new message.
 */
export const TenantSchema: GenMessage<Tenant> = /*@__PURE__*/
  messageDesc(file_budget_v1_tenant, 0);

/**
 * @generated from message budget.v1.TenantMembership
 */
export type TenantMembership = Message<"budget.v1.TenantMembership"> & {
  /**
   * @generated from field: budget.v1.Tenant tenant = 1;
   */
  tenant?: Tenant;

  /**
   * @generated from field: budget.v1.TenantRole role = 2;
   */
  role: TenantRole;

  /**
   * @generated from field: bool is_default = 3;
   */
  isDefault: boolean;
};

/**
 * Describes the message budget.v1.TenantMembership.
 * Use `create(TenantMembershipSchema)` to create a new message.
 */
export const TenantMembershipSchema: GenMessage<TenantMembership> = /*@__PURE__*/
  messageDesc(file_budget_v1_tenant, 1);

/**
 * @generated from message budget.v1.CreateTenantRequest
 */
export type CreateTenantRequest = Message<"budget.v1.CreateTenantRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * optional, server may generate
   *
   * @generated from field: string slug = 2;
   */
  slug: string;

  /**
   * @generated from field: string default_currency_code = 3;
   */
  defaultCurrencyCode: string;
};

/**
 * Describes the message budget.v1.CreateTenantRequest.
 * Use `create(CreateTenantRequestSchema)` to create a new message.
 */
export const CreateTenantRequestSchema: GenMessage<CreateTenantRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_tenant, 2);

/**
 * @generated from message budget.v1.CreateTenantResponse
 */
export type CreateTenantResponse = Message<"budget.v1.CreateTenantResponse"> & {
  /**
   * @generated from field: budget.v1.Tenant tenant = 1;
   */
  tenant?: Tenant;
};

/**
 * Describes the message budget.v1.CreateTenantResponse.
 * Use `create(CreateTenantResponseSchema)` to create a new message.
 */
export const CreateTenantResponseSchema: GenMessage<CreateTenantResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_tenant, 3);

/**
 * @generated from message budget.v1.ListMyTenantsRequest
 */
export type ListMyTenantsRequest = Message<"budget.v1.ListMyTenantsRequest"> & {
};

/**
 * Describes the message budget.v1.ListMyTenantsRequest.
 * Use `create(ListMyTenantsRequestSchema)` to create a new message.
 */
export const ListMyTenantsRequestSchema: GenMessage<ListMyTenantsRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_tenant, 4);

/**
 * @generated from message budget.v1.ListMyTenantsResponse
 */
export type ListMyTenantsResponse = Message<"budget.v1.ListMyTenantsResponse"> & {
  /**
   * @generated from field: repeated budget.v1.TenantMembership memberships = 1;
   */
  memberships: TenantMembership[];
};

/**
 * Describes the message budget.v1.ListMyTenantsResponse.
 * Use `create(ListMyTenantsResponseSchema)` to create a new message.
 */
export const ListMyTenantsResponseSchema: GenMessage<ListMyTenantsResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_tenant, 5);

/**
 * @generated from enum budget.v1.TenantRole
 */
export enum TenantRole {
  /**
   * @generated from enum value: TENANT_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TENANT_ROLE_OWNER = 1;
   */
  OWNER = 1,

  /**
   * @generated from enum value: TENANT_ROLE_ADMIN = 2;
   */
  ADMIN = 2,

  /**
   * @generated from enum value: TENANT_ROLE_MEMBER = 3;
   */
  MEMBER = 3,
}

/**
 * Describes the enum budget.v1.TenantRole.
 */
export const TenantRoleSchema: GenEnum<TenantRole> = /*@__PURE__*/
  enumDesc(file_budget_v1_tenant, 0);

/**
 * @generated from service budget.v1.TenantService
 */
export const TenantService: GenService<{
  /**
   * @generated from rpc budget.v1.TenantService.CreateTenant
   */
  createTenant: {
    methodKind: "unary";
    input: typeof CreateTenantRequestSchema;
    output: typeof CreateTenantResponseSchema;
  },
  /**
   * @generated from rpc budget.v1.TenantService.ListMyTenants
   */
  listMyTenants: {
    methodKind: "unary";
    input: typeof ListMyTenantsRequestSchema;
    output: typeof ListMyTenantsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_budget_v1_tenant, 0);

