// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/transaction.proto (package budget.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTransactionRequest, CreateTransactionResponse, DeleteTransactionRequest, DeleteTransactionResponse, GetTransactionRequest, GetTransactionResponse, ListTransactionsRequest, ListTransactionsResponse, UpdateTransactionRequest, UpdateTransactionResponse } from "./transaction_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service budget.v1.TransactionService
 */
export const TransactionService = {
  typeName: "budget.v1.TransactionService",
  methods: {
    /**
     * @generated from rpc budget.v1.TransactionService.CreateTransaction
     */
    createTransaction: {
      name: "CreateTransaction",
      I: CreateTransactionRequest,
      O: CreateTransactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.TransactionService.UpdateTransaction
     */
    updateTransaction: {
      name: "UpdateTransaction",
      I: UpdateTransactionRequest,
      O: UpdateTransactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.TransactionService.DeleteTransaction
     */
    deleteTransaction: {
      name: "DeleteTransaction",
      I: DeleteTransactionRequest,
      O: DeleteTransactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.TransactionService.GetTransaction
     */
    getTransaction: {
      name: "GetTransaction",
      I: GetTransactionRequest,
      O: GetTransactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.TransactionService.ListTransactions
     */
    listTransactions: {
      name: "ListTransactions",
      I: ListTransactionsRequest,
      O: ListTransactionsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

