// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file budget/v1/user.proto (package budget.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file budget/v1/user.proto.
 */
export const file_budget_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChRidWRnZXQvdjEvdXNlci5wcm90bxIJYnVkZ2V0LnYxIrcBCgRVc2VyEgoKAmlkGAEgASgJEg0KBWVtYWlsGAIgASgJEgwKBG5hbWUYAyABKAkSDgoGbG9jYWxlGAQgASgJEhYKDmVtYWlsX3ZlcmlmaWVkGAUgASgIEi4KCmNyZWF0ZWRfYXQYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIg4KDEdldE1lUmVxdWVzdCIuCg1HZXRNZVJlc3BvbnNlEh0KBHVzZXIYASABKAsyDy5idWRnZXQudjEuVXNlciI0ChRVcGRhdGVQcm9maWxlUmVxdWVzdBIMCgRuYW1lGAEgASgJEg4KBmxvY2FsZRgCIAEoCSI2ChVVcGRhdGVQcm9maWxlUmVzcG9uc2USHQoEdXNlchgBIAEoCzIPLmJ1ZGdldC52MS5Vc2VyIkcKFUNoYW5nZVBhc3N3b3JkUmVxdWVzdBIYChBjdXJyZW50X3Bhc3N3b3JkGAEgASgJEhQKDG5ld19wYXNzd29yZBgCIAEoCSIYChZDaGFuZ2VQYXNzd29yZFJlc3BvbnNlMvQBCgtVc2VyU2VydmljZRI6CgVHZXRNZRIXLmJ1ZGdldC52MS5HZXRNZVJlcXVlc3QaGC5idWRnZXQudjEuR2V0TWVSZXNwb25zZRJSCg1VcGRhdGVQcm9maWxlEh8uYnVkZ2V0LnYxLlVwZGF0ZVByb2ZpbGVSZXF1ZXN0GiAuYnVkZ2V0LnYxLlVwZGF0ZVByb2ZpbGVSZXNwb25zZRJVCg5DaGFuZ2VQYXNzd29yZBIgLmJ1ZGdldC52MS5DaGFuZ2VQYXNzd29yZFJlcXVlc3QaIS5idWRnZXQudjEuQ2hhbmdlUGFzc3dvcmRSZXNwb25zZUI4WjZnaXRodWIuY29tL3Bvc2l0cm9uNDgvYnVkZ2V0L2dlbi9nby9idWRnZXQvdjE7YnVkZ2V0djFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message budget.v1.User
 */
export type User = Message<"budget.v1.User"> & {
  /**
   * UUID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * e.g. "en", "ru"
   *
   * @generated from field: string locale = 4;
   */
  locale: string;

  /**
   * @generated from field: bool email_verified = 5;
   */
  emailVerified: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message budget.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_budget_v1_user, 0);

/**
 * @generated from message budget.v1.GetMeRequest
 */
export type GetMeRequest = Message<"budget.v1.GetMeRequest"> & {
};

/**
 * Describes the message budget.v1.GetMeRequest.
 * Use `create(GetMeRequestSchema)` to create a new message.
 */
export const GetMeRequestSchema: GenMessage<GetMeRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_user, 1);

/**
 * @generated from message budget.v1.GetMeResponse
 */
export type GetMeResponse = Message<"budget.v1.GetMeResponse"> & {
  /**
   * @generated from field: budget.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message budget.v1.GetMeResponse.
 * Use `create(GetMeResponseSchema)` to create a new message.
 */
export const GetMeResponseSchema: GenMessage<GetMeResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_user, 2);

/**
 * @generated from message budget.v1.UpdateProfileRequest
 */
export type UpdateProfileRequest = Message<"budget.v1.UpdateProfileRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string locale = 2;
   */
  locale: string;
};

/**
 * Describes the message budget.v1.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export const UpdateProfileRequestSchema: GenMessage<UpdateProfileRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_user, 3);

/**
 * @generated from message budget.v1.UpdateProfileResponse
 */
export type UpdateProfileResponse = Message<"budget.v1.UpdateProfileResponse"> & {
  /**
   * @generated from field: budget.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message budget.v1.UpdateProfileResponse.
 * Use `create(UpdateProfileResponseSchema)` to create a new message.
 */
export const UpdateProfileResponseSchema: GenMessage<UpdateProfileResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_user, 4);

/**
 * @generated from message budget.v1.ChangePasswordRequest
 */
export type ChangePasswordRequest = Message<"budget.v1.ChangePasswordRequest"> & {
  /**
   * @generated from field: string current_password = 1;
   */
  currentPassword: string;

  /**
   * @generated from field: string new_password = 2;
   */
  newPassword: string;
};

/**
 * Describes the message budget.v1.ChangePasswordRequest.
 * Use `create(ChangePasswordRequestSchema)` to create a new message.
 */
export const ChangePasswordRequestSchema: GenMessage<ChangePasswordRequest> = /*@__PURE__*/
  messageDesc(file_budget_v1_user, 5);

/**
 * @generated from message budget.v1.ChangePasswordResponse
 */
export type ChangePasswordResponse = Message<"budget.v1.ChangePasswordResponse"> & {
};

/**
 * Describes the message budget.v1.ChangePasswordResponse.
 * Use `create(ChangePasswordResponseSchema)` to create a new message.
 */
export const ChangePasswordResponseSchema: GenMessage<ChangePasswordResponse> = /*@__PURE__*/
  messageDesc(file_budget_v1_user, 6);

/**
 * @generated from service budget.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc budget.v1.UserService.GetMe
   */
  getMe: {
    methodKind: "unary";
    input: typeof GetMeRequestSchema;
    output: typeof GetMeResponseSchema;
  },
  /**
   * @generated from rpc budget.v1.UserService.UpdateProfile
   */
  updateProfile: {
    methodKind: "unary";
    input: typeof UpdateProfileRequestSchema;
    output: typeof UpdateProfileResponseSchema;
  },
  /**
   * @generated from rpc budget.v1.UserService.ChangePassword
   */
  changePassword: {
    methodKind: "unary";
    input: typeof ChangePasswordRequestSchema;
    output: typeof ChangePasswordResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_budget_v1_user, 0);

