// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file budget/v1/user.proto (package budget.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChangePasswordRequest, ChangePasswordResponse, GetMeRequest, GetMeResponse, UpdateProfileRequest, UpdateProfileResponse } from "./user_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service budget.v1.UserService
 */
export const UserService = {
  typeName: "budget.v1.UserService",
  methods: {
    /**
     * @generated from rpc budget.v1.UserService.GetMe
     */
    getMe: {
      name: "GetMe",
      I: GetMeRequest,
      O: GetMeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.UserService.UpdateProfile
     */
    updateProfile: {
      name: "UpdateProfile",
      I: UpdateProfileRequest,
      O: UpdateProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc budget.v1.UserService.ChangePassword
     */
    changePassword: {
      name: "ChangePassword",
      I: ChangePasswordRequest,
      O: ChangePasswordResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

